### ISSUE TITLE
DB path on disk

### ISSUE THREAD

**Issue by iglocska** [DevoInc/sightingdb#5]
https://github.com/DevoInc/sightingdb/blob/master/src/client/db.rs#L15
```
        Database {
            db_path: String::from("/tmp/sdb/"),
            db: HashMap::new(),
```

Is this overriden somewhere?

**Comment by stricaud** [comment]
For now this variable is not used, this is a good catch and I indeed must use the one defined in the configuration file.

**Comment by cudeso** [comment]
Hello @stricaud , seems the DB is not written to disk. Regardless if I create /tmp/sdb/ myself or not, nothing is written to disk. Writing and reading sightings does work.

Also tried with storage=ON_DISK (https://github.com/DevoInc/sightingdb/blob/master/src/daemon/sighting_configure.rs#L5) no success. I have no knowledge on Rust so this setting might not be related.

**Comment by cudeso** [comment]
@stricaud  sorry, too many browser tabs. Was supposed to go into https://github.com/stricaud/sightingdb/

**Comment by stricaud** [comment]
This is something on my plate, you can checkout the branch 'store_to_disk' on https://github.com/stricaud/sightingdb/tree/store_to_disk but for now it only writes. 
I am going to work on this very soon. But as of now those settings are ignored.

I am closing here, feel free to re-open on my repository if needed.
