### ISSUE TITLE
Absence of test suite

### ISSUE THREAD

**Issue by srikwit** [DevoInc/sightingdb#9]
Hi Team,

Could you kindly provide an initial set of test suites because it would help me validate the changes I can make to the code.

**Comment by stricaud** [comment]
You are in the wrong repository. 
As not everyone can sign the CLA, the development has moved to https://github.com/stricaud/sightingdb.

**Comment by srikwit** [comment]
Hi @stricaud, I am unable to raise issues in your fork of this repository. Can you let me know which version of SightingDB will be maintained for use in MISP.
I have also closed my pull request on the project here. Kindly review it on your repository.
